apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: server-%s
  labels:
    app: oj-k8s-server
    id: "%s"
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: node2/vscode-limit
            operator: Gt
            values: ["%s"]
        weight: 5
      - preference:
          matchExpressions:
          - key: node3/vscode-limit
            operator: Gt
            values: ["%s"]
        weight: 5
  containers:
  - name: server-%s
    image: server_20230323:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: vscode
      containerPort: 8443
    volumeMounts:
    - name: workspace-volume
      mountPath: "/config/workspace"
    resources:
      limits:
        memory: "512Mi"
      requests:
        memory: "300Mi"
  volumes:
  - name: workspace-volume
    persistentVolumeClaim:
      claimName: pvc-%s